### ISSUE TITLE
Visiting 'Artists' route is loading an excessive amount of requests

### ISSUE THREAD

**Issue by vincentjr** [DroptuneHQ/droptune#88]
Not sure if it's related to https://github.com/DroptuneHQ/droptune/issues/50

Visiting https://droptune.co/artists loads an insane amount of requests. My Macbook was about to take flight destined to reach orbit~~

<img width="569" alt="Screen Shot 2019-09-24 at 12 50 32 AM" src="https://user-images.githubusercontent.com/515723/65482059-ca621700-de65-11e9-9a76-291310760f21.png">

**Comment by Shpigford** [comment]
Thanks for the heads up! What browser were you using? And were you logged in?

**Comment by vincentjr** [comment]
Chrome, not logged in.

**Comment by Shpigford** [comment]
Most of these requests are external image requests for the artist thumbnail (which comes from Spotify). It's slightly related to #50 if only because progressively loading the page would prevent loading all of the images, but otherwise it's not really a "bug" per se and there's not a way to reduce the image requests given it's, functionally speaking, a page of photos.

Going to close for now since solving #50 would also solve this.
