### ISSUE TITLE
README doesn't included required Apple Music setup steps

### ISSUE THREAD

**Issue by danielwestendorf** [DroptuneHQ/droptune#96]
Following the [How to start](https://github.com/DroptuneHQ/droptune#how-to-start) steps in the README, an error is encountered when no `APPLE_PRIVATE_KEY` ENV variable is set. [Generating a private key](https://help.apple.com/developer-account/#/devcdfbb56a3?sub=dev0416b9004) following these steps successfully bypasses the error.

Additionally, there are `apple_app_key` and `apple_team_key` referenced in `app/models/apple_music.rb`, but I don't know where those come from.

**Comment by Shpigford** [comment]
I still haven't found a way to easily let people contribute to anything that requires Apple Music credentials. Primarily because App Key and Team Key are associated with a single developer account. Anyone can create those, but they require an Apple Developer account (which costs money).

The intermediary option could be to just have people drop in dummy credentials if only to bypass errors about missing variables, but it still wouldn't let you actually connect/import an Apple Music account.

**Comment by Shpigford** [comment]
Just added README items for this!
